default: &default
  adapter: postgresql
  encoding: unicode
  pool: 12
  template: template0

development:
  <<: *default
  database: public_asset_checker_development
  url: <%= ENV["DATABASE_URL"]%>

test:
  <<: *default
  database: public_asset_checker_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  database: public_asset_checker_production
  url: <%= ENV["DATABASE_URL"]%>
